rune_helper/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'champion#champgg'
  #get '/champion/runes', to: 'champion#rune_page', as: 'runes'
  #get '/champion/', to:'champion#rune_page', as: 'runes'

  root 'champion#index'
  
  resources :champion
  resources :runes

end

rune_helper/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rune_helper/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rune_helper/app/controllers/champion_controller.rb
require 'json'

class ChampionController < ApplicationController
	class << self 
		attr_accessor :CHAMPION_STATIC_DATA, :CHAMPION_RUNE_DATA, :champ_id, :num_champ, :total_num_champions
		attr_accessor :runes, :runes_styles
	end
	
	def get_champ_static_data
		key1 = 'RGAPI-1937462f-22d9-4d7b-85d9-b82765d2b73c'
		key2 = 'RGAPI-9cd40029-9515-4027-9b27-24d824124e4c'
		@url = 'https://na1.api.riotgames.com/lol/static-data/v3/champions?tags=image&locale=en_US&dataById=false&api_key=' + key2
		response = HTTParty.get(@url)
		#puts response
		self.class.CHAMPION_STATIC_DATA = response.parsed_response["data"]
		#puts self.class.CHAMPION_STATIC_DATA
		puts response.header

		#puts self.class.CHAMPION_STATIC_DATA["data"].size
		self.class.total_num_champions = self.get_num_champ()
		#puts @yolo
		return self.class.CHAMPION_STATIC_DATA
	end

	def get_data_for(champion)
		return self.class.CHAMPION_STATIC_DATA[champion]
	end

	def get_num_champ
		num_key = 'RGAPI-9cd40029-9515-4027-9b27-24d824124e4c'
		@num_url = 'https://na1.api.riotgames.com/lol/platform/v3/champions?api_key=' + num_key
		num_response = HTTParty.get(@num_url)
		#puts num_response
		#return num_response
		#puts self.class.CHAMPION_STATIC_DATA["data"].count
		puts num_response["champions"].count
		return num_response["champions"].count
	end

	def get_champ_rune_data(champion_id)
		ggkey = '36cecc2b9b2b8c380d1c56b403fc300a'
		@url_b = 'http://api.champion.gg/v2/champions/' + champion_id + '?elo=SILVER&limit=2&champData=hashes&api_key=' + ggkey
		#@champ_data_b = nil
		#puts @url_b
		@ggresponse = HTTParty.get(@url_b)
		self.class.CHAMPION_RUNE_DATA = @ggresponse.parsed_response[0]["hashes"]["runehash"]["highestWinrate"]["hash"]
		#puts @ggresponse
		return self.class.CHAMPION_RUNE_DATA
	end

	def index
		if self.class.CHAMPION_STATIC_DATA.nil? 
			puts "sending request"
			@champ_data = self.get_champ_static_data()
		else 
			puts "not sending request"
			@champ_data = self.class.CHAMPION_STATIC_DATA
		end
	end

	def show 
		@champ_name = params[:id]
		#puts params[:format]
		#puts params[:id]
		@champ_id = params[:format]
		puts @champ_id

		#if self.class.CHAMPION_RUNE_DATA.nil? 
		puts "sending request rune data"
		@rune_data = self.get_champ_rune_data(@champ_id)
		#puts @rune_data.split('-')
		@rune_data = @rune_data.split('-')
		puts @rune_data
		#puts Dir.pwd
		if self.class.runes.nil?
			runes = File.read('new_runes.json')
			runes = JSON.parse(runes)
			puts runes
		end
		if self.class.runes_styles.nil?
			runes_styles = File.read('rune_styles.json')
			runes_styles = JSON.parse(runes_styles)
			puts runes_styles
		end	
		#else 
		#	puts "not sending request rune data"
		#	@rune_data = self.class.CHAMPION_RUNE_DATA
		#end

	end

	#def champgg
	#	ggkey = '36cecc2b9b2b8c380d1c56b403fc300a'
	#	@url_b = 'http://api.champion.gg/v2/champions?elo=BRONZE&champData=hashes&limit=1&api_key=' + ggkey
	#	@champ_data_b = nil
	#	@ggresponse = nil
	#end
end

rune_helper/app/controllers/runes_controller.rb
class RunesController < ApplicationController
end

rune_helper/app/helpers/application_helper.rb
module ApplicationHelper
end

rune_helper/app/helpers/champion_helper.rb
module ChampionHelper
end

rune_helper/app/helpers/runes_helper.rb
module RunesHelper
end

rune_helper/app/views/champion/champgg.html.erb
hello! <br>

	<% if @champ_data_b.nil? %>
		<% puts 'dank' %>
		<% @ggresponse = HTTParty.get(@url_b) %>
		<!--% @champ_data_b = @ggresponse.parsed_response["elo"] %-->
		<% @champ_data_b = @ggresponse.parsed_response[0]["hashes"]["runehash"]["highestWinrate"]["hash"] %>
		<!--% puts @ggresponse[0]['elo'] %-->
		<% puts @champ_data_b %>
	<% end %>

rune_helper/app/views/champion/dank.html.erb
dank

rune_helper/app/views/champion/index.html.erb
<% @champ_data.each do |champion| %>
	<li>
		<%= link_to champion[0], champion_path(champion[0], champion[1]["id"]) %>
		<img src="https://ddragon.leagueoflegends.com/cdn/7.10.1/img/champion/<%=champion[1]["image"]["full"] %>">
		<!--% puts champion[1]["id"]%-->
	</li>
<% end %>

Go to Runes:
<button type="button" class="btn btn-primary">Runes</button>

rune_helper/app/views/champion/rune_page.html.erb
dank

rune_helper/app/views/champion/show.html.erb
This is the page for <%= @champ_name %>!
<%= @champ_info %>
Dank cuks <%= @rune_data%>

<% @rune_data.each_index do |rune_data| %>
	<li>
		<% puts rune_data %>
		<% puts "dank" %>
	</li>
<% end %>

rune_helper/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RuneHelper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>